language: bash

branches:
  only:
  - master

services:
  - docker

before_install:
  - docker build -t j-worker:v8 .

script:
  - docker run -it -d --rm j-worker:v8 /bin/sh -c "npm -version"
  - docker run -it -d --rm j-worker:v8 /bin/sh -c "jenkins-agent -version x"
  - docker run -it -d --rm j-worker:v8 /bin/sh -c "ansible --version"

    # jobs:
    #   include:
    #     - stage: test
    #       script: ./bash.sh
